Refactor/createbattle
eduardavercosa/theDudaProject pull request #36
Opened 2021-05-06 18:26 UTC by eduardavercosa

## Objective and Motivation
- Refactor the Create Battle to save the Players, the creator team, the creator Pokemons in the DB, and to give a success message in the end.

2021-05-07 20:00 UTC, rsarai requested changes

2021-05-07 20:00 UTC, rsarai commented on backend/battling/forms.py
>  class PokemonForm(forms.ModelForm):
The next form `PokemonForm2` should be deleted no?

2021-05-07 20:00 UTC, rsarai commented on backend/battling/forms.py
> +            "pokemon_1",
Is this the place to add pokemons?

2021-05-07 20:00 UTC, rsarai commented on backend/battling/urls.py
> +    path("battle/<int:pk>/details/", DetailBattle.as_view(), name="battle_details"),
nice! I will ask to keep the pattern: `<int:id>` or `<int:pk`

2021-05-07 20:00 UTC, rsarai commented on backend/battling/views.py
> +from django.views.generic.detail import DetailView
Imports should be `from django.views.generic import CreateView, DetailView`

2021-05-07 20:00 UTC, rsarai commented on backend/battling/views.py
> +class EnterBattle(CreateView):
Isn't this the same as `CreateBattle`? If yes, this should removed

2021-05-07 20:00 UTC, rsarai commented on backend/battling/views.py
> +        form.instance.creator = self.request.user
This is the only thing you need on this form. And still, I think the location could be improved.

2021-05-07 20:00 UTC, rsarai commented on backend/battling/views.py
> +        messages.success(self.request, "Your battle was created!")
This logic should be in a separate form to create the teams

2021-05-07 20:00 UTC, rsarai commented on backend/battling/forms.py
>  class PokemonForm(forms.ModelForm):
As we discussed, we should have one form to select the teams and another one to create battles

2021-05-07 20:00 UTC, rsarai commented on backend/battling/views.py
> +        return get_object_or_404(Battle, pk=id_)
This should not be required.

2021-05-07 21:08 UTC, eduardavercosa commented on backend/battling/forms.py
>  class PokemonForm(forms.ModelForm):
Yes, I deleted it, I just didn't send it in this PR, because I was waiting for the EditBattle PR, since the PokemonForm2 is for the Opponent Team.

2021-05-14 18:07 UTC, rsarai requested changes

2021-05-14 18:07 UTC, rsarai commented on backend/battling/forms.py
> +class CreatorForm(forms.ModelForm):
I think a better name would be `CreateBattleForm`

2021-05-14 18:07 UTC, rsarai commented on backend/battling/forms.py
> +class TeamForm(forms.ModelForm):
Let's keep the consistency here and do `CreateTeamForm`

2021-05-14 18:07 UTC, rsarai commented on backend/battling/forms.py
> +        PokemonTeam.objects.create(
The clean method is the place for validations, model creation should be on the `save` method

2021-05-14 18:07 UTC, rsarai commented on backend/battling/forms.py
> +        PokemonTeam.objects.create(
Here's some content to guide you:
- https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/#the-save-method
- https://www.djangotricks.com/tricks/Swv44PDSrJYQ/

2021-05-14 18:07 UTC, rsarai commented on backend/battling/urls.py
> +    path("team/<int:pk>/edit/", CreateTeam.as_view(), name="create_team"),
Hmm, why this changed?

2021-05-14 18:07 UTC, rsarai commented on backend/battling/urls.py
> +    path("battle/<int:pk>/join/", JoinBattle.as_view(), name="join_battle"),
Let's keep the consistency with other urls with: `battle/<int:pk>/edit/`

2021-05-14 18:07 UTC, rsarai commented on backend/battling/urls.py
> +    path("battle/<int:pk>/details/", DetailBattle.as_view(), name="battle_details"),
I think the url should be singular: `battle/<int:pk>/detail`

2021-05-14 18:07 UTC, rsarai commented on backend/battling/views.py
> +        if self.get_object().trainer == battle_creator:
you can already replace the `get_object` with the `self.request.user` and use the django admin login to test this

2021-05-14 18:07 UTC, rsarai commented on backend/battling/views.py
> +class JoinBattle(UpdateView):
Hey, what's your reasoning to create this view? Some inconsistencies I see here: 
- Your view has `Team` as a model but uses the `CreatorForm` which is related to `Battle`.
- You have a form but you never save it.

2021-05-14 18:07 UTC, rsarai commented on backend/battling/views.py
> +    def get_battle(self):
This should work by default, you can remove the `get_battle` and the `context_object_name`.

2021-05-21 12:30 UTC, rsarai requested changes

2021-05-21 12:30 UTC, rsarai commented on backend/battling/views.py
> +class EditBattle(UpdateView):
This will not be used anymore right? If yes, you can delete it

2021-05-21 12:30 UTC, rsarai commented on backend/battling/views.py
> +    def get_battle(self):
I believe this method is not required

2021-05-21 12:30 UTC, rsarai commented on backend/battling/forms.py
> +        PokemonTeam.objects.create(team=self.instance, pokemon=data["pokemon_1"], order=1)
What would happen if the edits the team twice? Will the team have 6 pokemons?

2021-05-24 19:50 UTC, rsarai commented on backend/battling/forms.py
> +            PokemonTeam.objects.filter(team=self.instance).delete()
You can use `self.instance.pokemons.clear()`
https://docs.djangoproject.com/en/3.2/topics/db/examples/many_to_many/

2021-05-24 19:51 UTC, rsarai commented on backend/battling/views.py
> +    def get_battle(self):
Is this required?

2021-05-26 13:31 UTC, rsarai approved these changes

2021-05-26 15:42 UTC, merged