Validation
eduardavercosa/theDudaProject pull request #77
Opened 2021-08-09 14:12 UTC by eduardavercosa

## Objective and Motivation
- Shows error if User challenges itself

2021-08-10 13:02 UTC, rsarai requested changes

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        self.auth_client.post(reverse("create-battle"), battle_data)
Please assert that the response is 403

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        self.auth_client.post(reverse("create-battle"), battle_data)
Assert that the response status is correct

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +    #     self.assertEqual(response.status_code, 200)
Why is this commented?

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        BattleSerializer([battle], many=True)
this is not being used, but please check if the contents are the same

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        BattleSerializer([battle], many=True)
same as before

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        BattleSerializer([battle], many=True)
```
response = self.auth_client.get(reverse("battle-list"))
expected_response = BattleSerializer([battle], many=True)
self.assertCountEqual(expected_response.data, response.json())
```

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        BattleSerializer([battle], many=True)
same as before

2021-08-10 13:02 UTC, rsarai commented on backend/battling/tests/test_endpoints.py
> +        BattleSerializer([battle2], many=True)
same as before, this is not being used

2021-08-13 13:02 UTC, rsarai requested changes

2021-08-13 13:02 UTC, rsarai commented on backend/templates/registration/invite_signup_email.html
> +{{ domain }}{% url 'signup_confirm' uidb64=uid token=token %}
You also need to add the `{{ protocol }}://` no? Or is this already on the domain?

2021-08-13 14:29 UTC, eduardavercosa commented on backend/templates/registration/invite_signup_email.html
> +{{ domain }}{% url 'signup_confirm' uidb64=uid token=token %}
It's already in the domain :D

2021-08-16 13:48 UTC, rsarai approved these changes

2021-08-16 13:55 UTC, merged