Create team endpoint
eduardavercosa/theDudaProject pull request #78
Opened 2021-08-10 16:48 UTC by eduardavercosa

## Objective and Motivation
- Create team endpoint

2021-08-16 14:21 UTC, rsarai requested changes

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/endpoints.py
> +    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
Should we use this permission?

2021-08-16 14:21 UTC, rsarai commented on backend/battling/forms.py
> +    has_repeated_pokemon_old,
why was this renamed? We should not add suffix with time constraints our code, this makes the code dated and hard to understand

2021-08-16 14:21 UTC, rsarai commented on backend/pokemon/helpers.py
> +def has_repeated_pokemon(pokemons_list):
We can't have two functions doing the same thing. In situations like this, we should refactor the multiple places of the code to use the same function.

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/endpoints.py
> +    serializer_class = BattleTeamSerializer
Why the `CreateTeam` endpoint is using a `BattleTeamSerializer`? The names here could be improved

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +    pokemon_teams = PokemonTeamSerializer(many=True, required=False)
I don't see the utility of this attribute, where are you thinking about using this?

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +class PokemonTeamSerializer(serializers.ModelSerializer):
I also don't see the utility of this serializer, what are your plans for this?

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/urls.py
> +    path("battles/team/<int:pk>/edit/", endpoints.CreateTeam.as_view(), name="create-team"),
There's no need for the prefix `battle` here, `team/<int:pk>/edit/` fits better

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +class BattleTeamSerializer(serializers.ModelSerializer):
I don't see a problem with having separated `read` and `write` serializers. But they need to be named accordingly and have the logic splitted. What was the reason for this change?

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +    team = TeamSerializer(read_only=True)
This is a read-only field and should not be used on a write-only serializer

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +    pokemons = PokemonSerializer(many=True, read_only=True)
Same thing here, this is a read-only field and should not be used on a write-only serializer

2021-08-16 14:21 UTC, rsarai commented on backend/battling/api/serializers.py
> +        return creator_pokemons and opponent_pokemons
This method should be in a separated place, since it can be used on the serializer and on the form

2021-08-16 19:51 UTC, eduardavercosa commented on backend/battling/api/endpoints.py
> +    serializer_class = BattleTeamSerializer
Because the BattleTeamSerializer is where I create the team.... but I'll change the names

2021-08-20 20:17 UTC, rsarai approved these changes

2021-08-23 14:06 UTC, merged