React
eduardavercosa/theDudaProject pull request #79
Opened 2021-08-19 16:55 UTC by eduardavercosa

- Start the FrontEnd feature with React

2021-08-20 21:06 UTC, rsarai requested changes

2021-08-20 21:06 UTC, rsarai commented on backend/duda/urls.py
> +        "react/battle/<int:pk>/detail",
What do you think of changing this prefix to something more meaningful? And extracting react URLs to another file?

2021-08-20 21:06 UTC, rsarai commented on backend/duda/urls.py
> +        name="react_template",
What about renaming this to remove the `react` prefix?

2021-08-20 21:06 UTC, rsarai commented on frontend/js/utils/api.js
> +  const url = `http://${baseUrl}/${urlApi}`;
We are using `django-js-reverse` to pass urls from django to react. Instructions on how to set this here: https://github.com/ierror/django-js-reverse#use-the-urls-in-javascript

2021-08-20 21:06 UTC, rsarai commented on frontend/js/utils/api.js
> +const apiUrls = {
This is not required since we are using `django-js-reverse`

2021-08-26 13:45 UTC, rsarai requested changes
Minor comments

2021-08-26 13:45 UTC, rsarai commented on backend/battling/v2/urls_v2.py
> +        name="spa_template",
The name of the url should be something meaningful, is this case: `battle_detail_v2`

2021-08-26 13:45 UTC, rsarai commented on backend/duda/settings/base.py
> +CORS_ALLOW_ALL_ORIGINS = True
Why are you changing this? This is changing the config for all our environments, we usually don't want to allow all hosts for the production server

2021-08-26 13:45 UTC, rsarai commented on frontend/js/utils/api.js
> +const getFromApi = () => {
Shouldn't this receive the `urlApi` parameter?

2021-08-26 14:44 UTC, eduardavercosa commented on frontend/js/utils/api.js
> +const getFromApi = () => {
It doesn't work if I put the parameter

2021-08-26 15:07 UTC, eduardavercosa commented on backend/battling/v2/urls_v2.py
> +        name="spa_template",
I did it in the show battle detail PR

2021-08-26 15:07 UTC, eduardavercosa commented on backend/duda/settings/base.py
> +CORS_ALLOW_ALL_ORIGINS = True
I removed it in the show battle detail PR

2021-09-08 18:16 UTC, rsarai approved these changes

2021-09-08 18:40 UTC, merged